### PR TITLE
3 new plugins (Mobile network credit, Travel card credit and network stats)

### PR DESCRIPTION
**Pull request by skhg**
Hello!

My first time submitting plugins to BitBar so hope everything is in order for you.

I've created 3 plugins which i'd like to submit:
* Display your current data balance and enabled bundles for [Tesco Mobile Ireland](https://github.com/skhg/BitBar-Plugins/tree/master/TescoMobileIrl)
* Display your [Leap Card](https://github.com/skhg/BitBar-Plugins/tree/master/LeapCard) balance and recent journeys
* Display IP address and some [useful network info](https://github.com/skhg/BitBar-Plugins/tree/master/NetworkInfo) 

Two of these are written in python and [require](https://github.com/skhg/pyleapcard) some [dependencies](https://github.com/skhg/pytescomobileirl) which are available through PyPi. The scripts check for these dependencies when run. I'm considering creating a bitbar-helper python package because some of the code is shared between these plugins.

Please let me know if any changes are required before you can merge this pull request. Thanks!

### CODE REVIEW

**Comment by tresni** [comment]
Hi @skhg and thank you for your contributions!  We use various linters (shellcheck and pyflakes in these cases) to check for common issues.  They have identified a number of potential warnings which we would need to see addressed before we merge your PR.  You can review the output at https://travis-ci.org/matryer/bitbar-plugins/builds/279067498?utm_source=github_status&utm_medium=notification .

**Comment by skhg** [comment]
@tresni Thanks for that, I will fix those errors and submit a follow-up pull request.

**Comment by tresni** [comment]
Fixed the last of the linter issues in 9488ce267d6e20fa23d3f2032aef699299f4d8b7 and 1d8f105505a74030b611f770fde6a8f1d2c66227

**Comment by skhg** [comment]
Hi @tresni 
I've been meaning to get back to this but with several job interviews recently I haven't had the chance to work on much else. Thanks for the merge and your fixes, i'll follow up on this when I can and ensure everything is working as expected with your changes.

**Pull request merged**
