### PR TITLE
Show lock/unlock icons for private/public transfers

### PR DESCRIPTION
**Pull request by rchiechi**

### CODE REVIEW

**Comment by rchiechi** [comment]
The Travis CI checker is parsing with python2 and (incorrectly) reporting a syntax error with print('string', end='').

**Comment by tresni** [comment]
Oi vey.  Good catch.  I'll update [.test.py](.test.py) to deal with python2 vs python3.

**Comment by tresni** [comment]
I believe we are just waiting on #515 and then we can re-run the test and get this merged.

**Comment by tresni** [comment]
hmm.. Not getting the latest travis.yml configuration.  Going to try closing/reopening to see if that does it..

**Comment by tresni** [comment]
That seemed to grab the right config so hopefully this will test properly :)

**Pull request merged**
