### PR TITLE
Update battery_cycles, add battery condition and max cycles

### PR DESCRIPTION
**Pull request by maxoumime**
Hi

I modified my script a bit, I added a refresh rate at 6 hours, not easy to find out because this can change with the un/plugging of the battery but 6 hours seems okay to me.
I also added a few indicators in the dropdown menu like the number of cycles on the maximum cycles number given by Apple (1000 for almost all the Macbooks from 2009), the color changes depending on the number of cycles (green < 750, orange < 1000, red > 1000). 
I wanted this maximum number to change depending on the model and year but despite the model is easy to find, the year isn't directly. You have to send the model number to a webservice, and I didn't want to send those informations (I added a href linking to the Apple section dedicated to batteries).

https://support.apple.com/en-us/HT201585

I also display the battery condition returned by the OS, with the color changing depending on that condition.

battery

### CODE REVIEW

**Comment by matryer** [comment]
LGTM - do you want to be the first to implement the Metadata for plugins to have your Plugin appear nicely here: http://getbitbar.appspot.com/plugins/System ?  See https://github.com/matryer/bitbar-plugins/issues/53

**Comment by maxoumime** [comment]
Wow sure that's a cool thing ! I add it right away

**Comment by maxoumime** [comment]
Aaaaand done :) Let's have a look

**Comment by matryer** [comment]
Looks great.

screen shot 2016-01-09 at 18 01 11

**Comment by matryer** [comment]
Plugins with metadata will appear closer to the top - makes the site more engaging.

**Comment by maxoumime** [comment]
Yeah it looks great ! 
And yeah that's a good point to order like that, more attractive indeed

**Comment by matryer** [comment]
see https://getbitbar.com/plugins/System for live version

**Pull request merged**
