### PR TITLE
Fix spotctl shorten function

### PR DESCRIPTION
**Pull request by Igor1201**
Fixes https://github.com/matryer/bitbar-plugins/issues/1197

### CODE REVIEW

**Comment by Igor1201** [comment]
Travis status is flaky :(

**Comment by Igor1201** [comment]
@matryer could you take a look, please?

**Comment by gingerbeardman** [comment]
You can close and reopen the PR to get Travis to try again, see #1214

**Comment by Igor1201** [comment]
Thanks @gingerbeardman

**Pull request closed without merging**
