### PR TITLE
QuakePlugIn Added

### PR DESCRIPTION
**Pull request by aaronedell**
Added a plugin for getting all significant earthquakes in the last 30
days

### CODE REVIEW

**Comment by matryer** [comment]
Excellent.

**Comment by matryer** [comment]
Do you live in California by any chance?

**Comment by matryer** [comment]
Can you rename the folder to `Environment`?

**Comment by aaronedell** [comment]
Goose idé.

**Comment by matryer** [comment]
(or even `Weather`?)

**Comment by aaronedell** [comment]
I changed the folder to Environment, clicked commit, then clicked sync. Did that work?

**Comment by matryer** [comment]
No. I'll do it.

**Pull request merged**
