### PR TITLE
Add plugin emacs-package-updates

### PR DESCRIPTION
**Pull request by masutaka**
This plugin gives the below information.

### CODE REVIEW

**Comment by tresni** [comment]
Squashed and merged as 7486d81.  I removed the abouturl as it shouldn't reference the bitbar-plugins github or website.  If you have your own website that you want to point it at, that would be an appropriate use.

**Comment by iosdeveloper** [comment]
@tresni The bitbar-plugins GitHub is used as about URL all over the place. ¯\_(ツ)_/¯

**Comment by masutaka** [comment]
@tresni Thanks a lot!

**Comment by tresni** [comment]
Maybe I'm just blind then.  Recirculated referencing seems weird though.

**Pull request closed without merging**
