### PR TITLE
Added Pomodoro Timer 🍅

### PR DESCRIPTION
**Pull request by gorangajic**
https://en.wikipedia.org/wiki/Pomodoro_Technique

SS

### CODE REVIEW

**Comment by gorangajic** [comment]
Haha just noticed #177 

nvm anyway it was fun

**Comment by keithamus** [comment]
@gorangajic you should see if you can bring any improvements to #177 - for example the wonderful use of emoji

**Comment by matryer** [comment]
hahaha see https://github.com/matryer/bitbar-plugins/issues/180

**Comment by keithamus** [comment]
@gorangajic if you want to run the script through [shellcheck](http://www.shellcheck.net/) and fix all of the errors, then as per #180 we'll merge it :smile:

**Comment by gorangajic** [comment]
didn't know about that tool :+1: 

updated

**Comment by keithamus** [comment]
@gorangajic did you perhaps forget to push?

**Comment by gorangajic** [comment]
updated now

**Pull request merged**
