### PR TITLE
Added ssid-info plugin

### PR DESCRIPTION
**Pull request by orjanb**

### CODE REVIEW

**Comment by keithamus** [comment]
It'd be great to get a screenshot of the menu open (even if you need to fake the data) :smile:

**Comment by orjanb** [comment]
Good catch, I'll make a new screenshot.

**Comment by tresni** [comment]
```
Projects/bitbar-plugins ●» ./.test.py Network/ssid_info.sh                                                                                                                                                                                                                                                                                                      « [master●]
ERR! /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Network/ssid_info.sh not executable

ERR! failed with 1 errors

Projects/bitbar-plugins ●»
```

Please `chmod +x` your script and we'll be good to merge!

**Comment by tresni** [comment]
I have to apologize, not sure how those got missed, but please update to deal with the ShellCheck errors from the travis-ci build.  (I've included them below)

```
In /Users/travis/build/matryer/bitbar-plugins/System/uptime.1m.sh line 10:
INFO=`uptime`
     ^-- SC2006: Use $(..) instead of legacy `..`.
In /Users/travis/build/matryer/bitbar-plugins/System/uptime.1m.sh line 11:
echo $INFO | awk -F'[ ,:\t\n]+' '{
     ^-- SC2086: Double quote to prevent globbing and word splitting.
In /Users/travis/build/matryer/bitbar-plugins/System/uptime.1m.sh line 36:
echo $INFO | tr "," "\n" | tail -n 2
     ^-- SC2086: Double quote to prevent globbing and word splitting.
ERR! /Users/travis/build/matryer/bitbar-plugins/System/uptime.1m.sh failed linting, see above errors
ERR! failed with 1 errors
```

**Comment by tresni** [comment]
And I'm a moron who didn't notice that those errors were for a totally different plugin.  Not sure why they came up in your PR.  Re-ran and as you can see, everything looks good!  Merging now!

**Pull request merged**
