### PR TITLE
Revert recent commits to fix lint warnings flagged by a disabled rule.

### PR DESCRIPTION
**Pull request by sohocoke**
Fixes regression for mdf.1m.sh where rendering colour is incorrect when disk capacity is low.

### CODE REVIEW

**Comment by sohocoke** [comment]
@tresni a quick question with the shellcheck linting: doesn't the commit below specify that rules SC2206 and SC2207 should be excluded?

https://github.com/matryer/bitbar-plugins/commit/9bebf98953dcb98d4b1dc52887b1b058b60600f7#diff-2f227f602f9e62ae3a54903dcca58585R95

This is a reversion of the changes specifically for those linting rules in #1104, since the script was written with extensive usage of conversions between space-delimited strings and arrays that were non-trivial to re-write just to satisfy linting warnings.

**Comment by tresni** [comment]
Close. We ignore new lint codes for existing code. If a plugin is touched for any reason, or a new plugin is added, we require that it pass the full suite of linter tests.

**Comment by gingerbeardman** [comment]
Please solve the outstanding Travis CI issue(s) so this can be merged! Many thanks.

You can close and reopen the PR to get Travis to try again, see #1214

**Comment by sohocoke** [comment]
@gingerbeardman #1214 appears to be about the build occasionally failing to download deps. This PR is failing CI due to existing code that was committed prior to this PR which now fails lint rules which are getting re-applied. Unless the lint rules have changed, re-running CI would result in the same failure.

I can’t commit to fixing all those lines in the brittle shell script that I didn’t write, and ensuring no regressions, just to pass new lint rules for a plugin for a project which is now hardly maintained — e.g. https://github.com/matryer/bitbar/issues/504 is about the CI for the BitBar project that is broken and is blocking all PR’s since 2017. 

I would suggest changing the lint policy so new PR’s don’t get barred by new lint failures to old code, but since the project doesn’t seem really maintained, it feels like a lost cause.

Closing the PR since it will probably never be merged.

**Comment by gingerbeardman** [comment]
I agree with your thoughts on all of this. Thanks for your contributions.

**Pull request closed without merging**
