### PR TITLE
added jira plugin

### PR DESCRIPTION
**Pull request by ngehlert**
added bitbar plugin for jira that displays all blockers, assigned tasks and open storys.

### CODE REVIEW

**Comment by matryer** [comment]
Can you please update to the actual image URL rather than the imgur url? :)

**Comment by ngehlert** [comment]
sorry my bad :)
done

**Comment by dkhamsing** [comment]
nice image :grin:

**Comment by tresni** [comment]
Hi, we are using shellcheck to lint all shell based plugins.  Please address the following and I'll get this merged:

```
Projects/bitbar-plugins ●» ./.test.py Dev/Jira/jira.1m.sh                                                                                                                                                                                                                                                                                                       « [master●]

In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 25:
  awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
                                             ^-- SC2086: Double quote to prevent globbing and word splitting.
                                                                                               ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 31:
  awk -F"[:}]" '{for(i=1;i<=NF;i++){if($i~/'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
                                            ^-- SC2086: Double quote to prevent globbing and word splitting.
                                                                                              ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 39:
  while [ $i -le $numberOfTasks ]
                 ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 44:
    echo $key: $issues "| bash=$0 param1=$url terminal=false color=$color"
         ^-- SC2086: Double quote to prevent globbing and word splitting.
               ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 50:
  login=$(curl --insecure --silent -X POST -H "Content-Type: application/json" -H "X-Atlassian-Token: nocheck" -c ${COOKIE_LOCATION} --data "{\"username\":\"${USER}\",\"password\":\"${PASSWORD}\"}" "${JIRA_BASE_URL}/rest/auth/1/session")
  ^-- SC2034: login appears unused. Verify it or export it.
                                                                                                                  ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 54:
  recursive=$1
  ^-- SC2034: recursive appears unused. Verify it or export it.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 55:
  blocker=$(curl --insecure --silent -X GET -b ${COOKIE_LOCATION} -H "Content-Type: application/json" $JIRA_BASE_URL/rest/api/2/search?jql=sprint%20in%20openSprints\(\)AND%20priority=Blocker%20AND%20project=${PROJECT}%20AND%20status\!=done\&fields=summary)
                                               ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 57:
  assignedTasks=$(curl --insecure --silent -X GET -b ${COOKIE_LOCATION} -H "Content-Type: application/json" $JIRA_BASE_URL/rest/api/2/search?jql=assignee%20in\(currentUser\(\)\)AND%20sprint%20in%20openSprints\(\)AND%20status\!=done\&fields=summary)
                                                     ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 59:
  stories=$(curl  --insecure --silent -X GET -b ${COOKIE_LOCATION} -H "Content-Type: application/json" $JIRA_BASE_URL/rest/api/2/search?jql=sprint%20in%20openSprints\(\)%20AND%20issuetype=story%20AND%20project=${PROJECT}%20AND%20status\!=done\&fields=summary)
                                                ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 67:
      if [[ recursive == true ]]
                      ^-- SC2050: This expression is constant. Did you forget the $ on a variable?


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 77:
  if [ $totalBlocker -gt 0 ]
       ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 79:
      echo Blocker: ${totalBlocker} "| color=#F44336"
                    ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 81:
      echo Tasks assigned: ${totalAssignedTasks} "| color=#333333"
                           ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 86:
  echo Blocker: ${totalBlocker} "| color=#333333"
                ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 90:
  echo Tasks assigned: ${totalAssignedTasks} "| color=#333333"
                       ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 94:
  echo Open Stories: ${totalStories} "| color=#333333"
                     ^-- SC2086: Double quote to prevent globbing and word splitting.


In /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh line 104:
  open $1
       ^-- SC2086: Double quote to prevent globbing and word splitting.

ERR! /Volumes/Home/bhartvigsen/Documents/Projects/bitbar-plugins/Dev/Jira/jira.1m.sh failed linting, see above errors

ERR! failed with 1 errors
```

**Comment by ngehlert** [comment]
sorry didn't know about shellcheck q.q
it's fixed now

**Pull request merged**
