### PR TITLE
Handle spaces in script path and menu icons

### PR DESCRIPTION
**Pull request by torkelsson**
A two folded PR (sorry). 

The first one for handle spaces in the script path.
The second adds icons to the menu entries.

### CODE REVIEW

**Comment by tresni** [comment]
@jtokoph - Wanna take a look at this?

@torkelsson - You may want to bump the version.

**Comment by tresni** [comment]
I think you need to rebase your branch on current master.  You ended up with a lot of junk in your branch ;-)

**Comment by torkelsson** [comment]
Yeah, I should learn how to branch before doing PRs and continuing with other stuff ;-)
Please Kill this PR so I can do it the (hopefully) right way :-)

**Comment by tresni** [comment]
Closing per request.

**Pull request closed without merging**
