### PR TITLE
Add option to manage global agents

### PR DESCRIPTION
**Pull request by robin-moser**

### CODE REVIEW

**Comment by gingerbeardman** [comment]
Please correct the Travis-CI error (click Details above to see it)

**Comment by matryer** [comment]
@robin-moser please fix conflicts and I'll merge this in today.

**Comment by gingerbeardman** [comment]
Please solve the outstanding Travis CI issue(s) so this can be merged! Many thanks.

You can close and reopen the PR to get Travis to try again, see #1214

**Comment by robin-moser** [comment]
Hi @gingerbeardman,
I totally missed the feature branch, sorry about that. I reafactored the code and fixed all shellcheck errors. The Version number is dumped and the plugin screenshot is updated. Thanks for checking it out.

**Pull request merged**
