### PR TITLE
Plugin keyboard-symbol.py

### PR DESCRIPTION
**Pull request by dqhieu**

### CODE REVIEW

**Comment by matryer** [comment]
Please make the plugin executable - https://travis-ci.org/matryer/bitbar-plugins/builds/147436531

**Comment by dqhieu** [comment]
@matryer the log says: /Users/travis/build/matryer/bitbar-plugins/System/keyboard-symbol.py **not executable**, but when I run this file on my mac, it work fine. Please help me!!!

**Comment by matryer** [comment]
Do `chmod +x keyboard-symbol.py` to set execution flag and then push that change?

**Comment by keithamus** [comment]
@dqhieu if you run `chmod +x System/keyboard-symbol.py` and then `git add System/keyboard-symbol.py` and `git commit -m'make keyboard-symbol.py executable'`

**Comment by dqhieu** [comment]
It works!!! Thank you very much!

**Pull request closed without merging**
