### PR TITLE
add watson status plugin

### PR DESCRIPTION
**Pull request by toin0u**
A simple script which displays Watson's status (project name, started time and tags)
- http://tailordev.github.io/Watson/

### CODE REVIEW

**Comment by willdurand** [comment]
Awesome!

**Comment by keithamus** [comment]
@toin0u could you please quote all variables to prevent the word splitting that occurs with spaces in bash. Thanks :smile:

**Comment by toin0u** [comment]
@keithamus Done :)

**Comment by toin0u** [comment]
Thank you!

**Comment by matryer** [comment]
No, thank you - plugin contributions is what makes BitBar awesome.

**Comment by jmaupetit** [comment]
Thank you @toin0u ! :heart:

**Pull request merged**
