### PR TITLE
Adding ether tu euro rate from kraken

### PR DESCRIPTION
**Pull request by ggrelet**
Adding a plugin that fetch the Ether/Euro rate at www.kraken.com

ether-eur-kraken

Thanks to @monerohow for the Kraken API pattern.

### CODE REVIEW

**Comment by tresni** [comment]
You've got a couple linting issues to address before we can merge:
```
In /Users/travis/build/matryer/bitbar-plugins/Cryptocurrency/Ethereum/ether-eur-kraken.30s.sh line 14:
echo "`printf "Ξ %.3f \n" "$val"` | size=13"
      ^-- SC2006: Use $(..) instead of legacy `..`.
In /Users/travis/build/matryer/bitbar-plugins/Cryptocurrency/Ethereum/ether-eur-kraken.30s.sh line 16:
echo "Kraken.com | href="https://www.kraken.com/""
                         ^-- SC2140: Word is of the form "A"B"C" (B indicated). Did you mean "ABC" or "A\"B\"C"?
```

**Comment by ggrelet** [comment]
Thanks @tresni, corrected them all.

**Comment by tresni** [comment]
@ggrelet Sorry about this but I need to request one more change (sorry I failed to notice it before.)  Please remove the `<bitbar.image>` and `<bitbar.abouturl>` metadata lines or change them to actual URLs.

**Comment by ggrelet** [comment]
@tresni, I wish I could provide the image attached to my first post, but where's the best place to upload it on GitHub?
Also, the `abouturl` could be from www.getbitbar.com but the plugin isn't published yet, will I be able to change it later?

**Comment by ggrelet** [comment]
I hosted an image my personal repo, and then changed the metadata.

**Comment by tresni** [comment]
Sorry, but you can't put the image in your PR.  My recommendation would be to upload it to imgur.com or other image hosting service that allows hotlinking.

**Comment by ggrelet** [comment]
Ok, got it right.

**Pull request merged**
