### PR TITLE
Update GitHub Notifications to work with Python 3

### PR DESCRIPTION
**Pull request by fenhl**
Tested with Python 3, not tested with Python 2. Hope I didn't break anything.

### CODE REVIEW

**Comment by fenhl** [comment]
I seem to have broken the plugin somehow. Do not merge, further investigation required.

**Comment by tresni** [comment]
@fenhl were you requesting that we not merge due to the travis build failing?  That was actually due to changes in how python was handled by homebrew (which I've now fixed), not your plugin in particular.  I won't merge unless you say it's okay though ;-)

**Comment by fenhl** [comment]
No, this version of the plugin just doesn't show any notifications. I've started a more thorough overhaul to fix it, and it's working again for me, but it's still missing GitHub Enterprise support.

**Comment by gingerbeardman** [comment]
Oops ignore my last edit. Sorry! Will merge this as soon as you have it working.

**Comment by tresni** [comment]
Closing, you can reopen when you're ready!

**Pull request closed without merging**
