### PR TITLE
new plugin: Launch Agents

### PR DESCRIPTION
**Pull request by rnkn**
This plugin, influenced by the `brew-services` plugin, views and manages user Launch Agents (in `~/Library/LaunchAgents/`).

### CODE REVIEW

**Comment by tresni** [comment]
A couple issues in the Travis CI build: https://travis-ci.org/matryer/bitbar-plugins/builds/194791842 .  Please review and correct so we can merge!

**Comment by rnkn** [comment]
I saw those. I disagreed with Travis and put my reasons in the commit message.

**Comment by tresni** [comment]
If you feel they are not required, you can suppress the messages by adding a `# shellcheck disable=[ERROR_CODE]` directive on the line preceding each flagged line.  But we won't merge if the checks fail.

**Comment by rnkn** [comment]
Rewrote it to avoid these pitfalls. Rebased to a single commit for neatness.

**Comment by rnkn** [comment]
Cool. When does this become publicly available on getbitbar.com?

**Pull request merged**
