### PR TITLE
Adding additional details as multi-line menu

### PR DESCRIPTION
**Pull request by rakesh1988**
with the flag, I thought having the IP address and ISP provider name would be helpful.
adding a new plugin just for these additional feature is an overkill. hence proposing change to what is available.
Hope @MatzFan is ok with this.

### CODE REVIEW

**Comment by gingerbeardman** [comment]
Please solve the outstanding Travis CI issue(s) so this can be merged! Many thanks.

**Comment by gingerbeardman** [comment]
Please solve the outstanding Travis CI issue(s) so this can be merged! Many thanks.

You can close and reopen the PR to get Travis to try again, see #1214

**Comment by rakesh1988** [comment]
closing PR

**Comment by rakesh1988** [comment]
re opening PR

**Pull request merged**
