### PR TITLE
Add Cloudflare DNS

### PR DESCRIPTION
**Pull request by fortran01**

### CODE REVIEW

**Comment by gingerbeardman** [comment]
Please solve the outstanding Travis CI issue(s) so this can be merged! Many thanks.

**Comment by gingerbeardman** [comment]
Please solve the outstanding Travis CI issue(s) so this can be merged! Many thanks.

You can close and reopen the PR to get Travis to try again, see #1214

**Comment by fortran01** [comment]
@gingerbeardman any hints why Travic is stuck at 'Job received'? 🙏

**Comment by tresni** [comment]
Because I re-ran travis CI for almost every pull request, it'll only do ~5 per project at time and we have 50 currently.

**Pull request merged**
