### PR TITLE
Update slack-unread.1s.py

### PR DESCRIPTION
**Pull request by notiv-nt**
- Add private messages
- Add total messages count indicator
- Add link to the api.slack when user does not set token
- Remove channels in which the user is not a member
- Improved debugging
- Code refactor
- Add: open slack on icon click

image

image

### CODE REVIEW

**Comment by notiv-nt** [comment]
🖐

**Comment by tresni** [comment]
Hi @notiv-nt , I'm not sure if I'm suppose to take that emoji to mean "high five, ready to go" or "stop, please wait."  Can you please reply and let me know!  Thanks!

**Comment by notiv-nt** [comment]
@tresni high five

**Comment by notiv-nt** [comment]
anything else to add?

**Pull request merged**
