### PR TITLE
New Plugin: Hacker News Headlines Lite

### PR DESCRIPTION
**Pull request by amrrs**
Python based and does not display a lot of information (unlike the existing Ruby based Plugin).

Changes:

* Internet Connection Check
* Making code executable

### CODE REVIEW

**Comment by amrrs** [comment]
Ref: https://github.com/matryer/bitbar-plugins/pull/1071

**Comment by amrrs** [comment]
I tried to make it executable by doing `chmod +x` and `chmod 777` but still when i upload it to github the tests fail. Any help?

**Comment by tresni** [comment]
I got ya :)

**Comment by amrrs** [comment]
thank you :)

**Pull request closed without merging**
