### PR TITLE
add Average Review Times Plugin

### PR DESCRIPTION
**Pull request by mfks17**
This is a plugin to show average review times iOS & Mac App Store.
See also [my repository](https://github.com/mfks17/bitbar-plugin-AppStore).

### CODE REVIEW

**Comment by iosdeveloper** [comment]
Nice! Please use `raw` instead of `blob` for the image URL.

**Comment by mfks17** [comment]
I fixed image Metadata to use the raw file.

**Comment by iosdeveloper** [comment]
👍

**Comment by tresni** [comment]
Should this be under Dev instead of Web? Seems more geared towards development then general web stuff. @matryer opinion?

**Comment by tresni** [comment]
Merged but moved to Dev/AppStore.

**Comment by mfks17** [comment]
Thanks!  🙏

**Pull request merged**
