### PR TITLE
Update to the todoNotePlan script

### PR DESCRIPTION
**Pull request by raguay**
Many changes to the todoNotePlan script.

### CODE REVIEW

**Comment by raguay** [comment]
Lot's of fixes and new features.

**Comment by tresni** [comment]
Please increment [the version metadata](https://github.com/raguay/bitbar-plugins/blob/ad403e7bf516554cc3076ee21f94814b18779aa4/Lifestyle/todoNotePlan.15m.rb#L5).  Also is the screenshot still a good representation?

**Comment by raguay** [comment]
Okay. Updated the version meta. Sorry, I keep forgetting about that.

**Comment by raguay** [comment]
yes. The screen shot is still fine. The changes were finer grained than you can tell in it. Mostly, more options for the user of the script.

**Pull request merged**
