### PR TITLE
Smile plugin.

### PR DESCRIPTION
**Pull request by irstacks**
:smile:

### CODE REVIEW

**Comment by tresni** [comment]
This is not properly rebased on master.

```sh
git remote add upstream https://github.com/matryer/bitbar-plugins.git
git fetch upstream
git checkout smile-plugin
git rebase upstream/master
# Fix merge errors
git push --force origin smile-plugin #assuming your repo is origin
```

Next time you start a new plugin do the following:

```sh
git fetch upstream
git checkout upstream/master -b new-plugin
```

That should keep your history clear of anything except your new plugin.

**Comment by irstacks** [comment]
Thanks for the tips on the clean history. That annoyed me too.  Will try to to keep the commits spick and span next time.

**Comment by tresni** [comment]
Hmm..  Not sure why all that history is coming with you... Try this:

``` sh
git checkout smile-plugin -b new-smile # Checkout a new branch based on the old branch so we retain the commit
git checkout upstream/master -B smile-plugin # Checkout upstream/master over top of old branch
git cherry-pick 75b4667 # Cherry-pick the commit into our new smile-plugin branch
git log # Make sure you are good here and everything is as expected!
git push origin smile-plugin --force # Push it to github
git branch -D new-smile # Delete the temp holding branch we don't need
```

As for the "errors" reported by `shellcheck`.  It's simply doesn't understand the reference to the categories.  You can safely suppress those errors (`# shellcheck disable=SC2034` on the line preceeding.)  See https://github.com/koalaman/shellcheck/wiki/SC2034 for more information.

**Comment by matryer** [comment]
I love this plugin - @irstacks can you please get those final errors solved so we can get this added to the repo?

**Comment by irstacks** [comment]
Awesome, thanks @matryer.

@tresni I wound up doing the following
```bash
$ git checkout master
$ git reset --hard upstream/master
$ git branch -b new-smile
$ git cherry-pick f9417b5 # (different commit cuz my earlier tanglings)
$ git push origin new-smile:smile-plugin --force
```

Knocking the shellcheckers off now.

**Comment by irstacks** [comment]
There are quite a few emojis that don't properly emoji-ize. I left em because

1. I'm too lazy to go through and pluck them out.
2. They'll still work for Github/Slack/etc.

I don't know where to begin addressing the issue w/r/t to BitBar's emojification-izer, but would be happy to pitch in if I can.

**Comment by iosdeveloper** [comment]
@irstacks See matryer/bitbar#312

**Comment by irstacks** [comment]
Noted, @iosdeveloper, thanks.

**Comment by tresni** [comment]
Some of those aren't Unicode emoji.  That includes most of the ones you pointed out.  Unless you felt like attempting to supply an image for those where appropriate, I don't think it's worth worrying about ;-)

Merging this in!

**Pull request merged**
