### PR TITLE
Added hour_logger plugin

### PR DESCRIPTION
**Pull request by udeyrishi**

### CODE REVIEW

**Comment by manojlds** [comment]
I think we are using the convention that the image points to a screenshot of the bitbar plugin. Can you update that please?

**Comment by matryer** [comment]
Yes we are - nice logo though :)

**Comment by matryer** [comment]
@udeyrishi can you update the image please and I'll merge this in?

**Comment by udeyrishi** [comment]
@matryer Sorry, was away for a while. Updated now. Thanks!

**Pull request merged**
