### PR TITLE
Add kubecontext plugin

### PR DESCRIPTION
**Pull request by copland**
This plugin helps with managing a number of kubeconfig contexts. It displays the currently active context in the menubar and allows you to easily switch between contexts.

### CODE REVIEW

**Comment by copland** [comment]
The travis-ci jobs appear to be hanging before startup.

**Comment by tresni** [comment]
Looks like you have the plugin in there twice.  Once in the Dev/Kubernetes folder and once in the root directory.  Please remove the one from the root directory.

**Comment by copland** [comment]
Ah, oops - copy error. I have removed the plugin from root.

**Comment by tresni** [comment]
Thanks for the contribution! You should see the plugin on the getbitbar.com page within ~24 hours (the website rebuilds once a day.)

**Pull request merged**
