### PR TITLE
add Semaphoreci project list plugin

### PR DESCRIPTION
**Pull request by gorangajic**
preview

### CODE REVIEW

**Comment by matryer** [comment]
Please update the README with your plugin name and contributor list too.

**Comment by gorangajic** [comment]
done

**Comment by matryer** [comment]
Nice work :)

**Comment by gorangajic** [comment]
Thank you for this awesome project :smile:

**Comment by matryer** [comment]
You are most welcome - I'm so pleased it's useful. That's all us developer ever really want isn't it? :)

**Pull request merged**
