### PR TITLE
Add WallpaperBing

### PR DESCRIPTION
**Pull request by tokfrans03**
This will change your desktop wallpaper to Bing's daily one. (or one from the week)

https://github.com/tokfrans03/BitBar-Bing-Wallpaper

P.S Github is confusing

### CODE REVIEW

**Comment by tokfrans03** [comment]
Why do I get this error?

ERR! /Users/travis/build/matryer/bitbar-plugins/Lifestyle/wallpaperbing.1h.sh not executable

**Comment by gingerbeardman** [comment]
Please solve the outstanding Travis CI issue(s) so this can be merged! Many thanks.

You can close and reopen the PR to get Travis to try again, see #1214

**Comment by AbbMarPin** [comment]
Sorry for not being too active here, I’ll make the file actually executable tomorrow or late in the week

**Comment by tokfrans03** [comment]
Sorry for not being too active here, I’ll make the file actually executable tomorrow or later in the week

**Pull request merged**
