### PR TITLE
Fixes & Additions

### PR DESCRIPTION
**Pull request by impshum**
Cryptonator wasn't working [(see here)](https://github.com/matryer/bitbar-plugins/issues/783). 
Changed over to Coinmarketcap.
Added Dash, Ripple, Monero, Etherium and Lisk tickers.

### CODE REVIEW

**Comment by tresni** [comment]
It doesn't look like you are on the latest masters as this is showing hundreds of changes to existing plugins.

```
git remote add upstream git@github.com:matryer/bitbar-plugins.git
git fetch upstream
git rebase upstream/master master
git push --force origin master
```

I think that'll do the trick, but don't quote me on it, YMMV, everything might explode.  Other option would be to checkout a new branch based on upstream/master and make your change there:

```
git remote add upstream git@github.com:matryer/bitbar-plugins.git
git fetch upstream
git checkout upstream/master -b update-the-plugin
git cherry-pick 6ee5552365fa0af3c0d2d1738a37700716621b7f
git cherry-pick 128c0a84158730ae83e0a145c9fba0e79dd2bfc3
git push origin update-the-plugin
```

Open a new PR for the update-the-plugin branch.

**Comment by impshum** [comment]
That should do the trick.

**Comment by tresni** [comment]
Can you please correct the permissions on `.gitignore` and `README.md` [see this](https://github.com/matryer/bitbar-plugins/pull/784/files?diff=split#diff-352040537ac03823d626166e25a5aa59).  

```
chmod 0644 .gitignore README.md
git add .gitignore README.md
git commit -m "revert file permissions"
git push origin master
```

**Comment by impshum** [comment]
Done.

**Pull request merged**
