### PR TITLE
Update Directory

### PR DESCRIPTION
**Pull request by dkhamsing**
Include a small script to generate the plugin directory.. would be cool if it updated the readme but that is done manually.. :sweat_smile: 

screen shot 2016-01-08 at 11 42 25 am

Look here to see what it looks like https://github.com/dkhamsing/bitbar-plugins/blob/directory/README.md

Because it is generated.. it does lose the extended description 🤔

### CODE REVIEW

**Comment by matryer** [comment]
Very cool. I wonder if the total should go into the header? Available plugins (`count`)

**Comment by matryer** [comment]
Would it be easy to parse the filenames so that `brew-updates.sh` becomes `Brew Updates`?

**Comment by dkhamsing** [comment]
Let me make a change to the header

**Comment by dkhamsing** [comment]
Added the header

**Comment by dkhamsing** [comment]
Mat I took a first pass at the script names and got

#### AWS
- [Elb](AWS/elb.30s.sh) `shell`

#### Bitcoin

##### bitstamp.net
- [Last](Bitcoin/bitstamp.net/last.10s.sh) `shell`

##### coinbase.com
- [Balance](Bitcoin/coinbase.com/balance.1h.sh) `shell`
- [Buy And Sell](Bitcoin/coinbase.com/buy-and-sell.10s.sh) `shell`
- [Buy](Bitcoin/coinbase.com/buy.10s.sh) `shell`
- [Sell](Bitcoin/coinbase.com/sell.10s.sh) `shell`
- [Spotrate](Bitcoin/coinbase.com/spotrate.10s.sh) `shell`

##### winkdex.com
- [Winkdex](Bitcoin/winkdex.com/winkdex.1m.sh) `shell`

#### Dev

##### Docker
- [Docker Status](Dev/Docker/docker-status.1m.sh) `shell`

##### GitHub
- [Notifications](Dev/GitHub/notifications.30s.py) `python`
- [Pull Requests](Dev/GitHub/pull-requests.5m.sh) `shell`

##### Homebrew
- [Brew Updates](Dev/Homebrew/brew-updates.1h.sh) `shell`

##### Jenkins
- [Jenkins Status](Dev/Jenkins/jenkins-status.1m.sh) `shell`

##### RescueTime
- [Rescuetime](Dev/RescueTime/rescuetime.1h.py) `python`

##### Semaphoreci
- [Project List](Dev/Semaphoreci/project-list.5m.js) `javascript`

##### Travis
- [Travis Check](Dev/Travis/travis-check.2m.py) `python`

##### Xcode
- [Xcode Version](Dev/Xcode/xcode-version.1h.sh) `shell`

#### Finance
- [Currency Tracker](Finance/currency-tracker.py) `python`
- [Stock](Finance/stock.5s.sh) `shell`
- [Yahoo Stock](Finance/yahoo-stock.1m.sh) `shell`

#### Lifestyle
- [Current Task](Lifestyle/current_task.1m.rb) `ruby`
- [Sleepingtime](Lifestyle/sleepingtime.1m.sh) `shell`

#### Music
- [Cmus](Music/cmus.10s.sh) `shell`
- [Itunes](Music/itunes.10s.sh) `shell`
- [Spotify](Music/spotify.10s.sh) `shell`
- [Vox](Music/vox.30s.sh) `shell`

#### Network
- [Bandwidth](Network/bandwidth.1s.sh) `shell`
- [External Ip](Network/external-ip.1h.sh) `shell`
- [Internal Ip](Network/internal-ip.1h.sh) `shell`
- [Ping](Network/ping.10s.sh) `shell`
- [Vpn Check](Network/vpn-check.3s.sh) `shell`
- [Website Status](Network/website-status.sh) `shell`
- [Wifiname](Network/wifiname.sh) `shell`

#### System

##### Battery
- [Battery Cycles](System/Battery/battery_cycles.sh) `shell`
- [Keyboard](System/Battery/keyboard.1m.sh) `shell`
- [Mouse](System/Battery/mouse.1m.sh) `shell`
- [Trackpad](System/Battery/trackpad.1.sh) `shell`
- [Trackpad](System/Battery/trackpad.1m.sh) `shell`
- [Clipboard History](System/clipboard-history.3s.sh) `shell`
- [Lock Screen](System/lock-screen.10h.sh) `shell`
- [Memusage](System/memusage.5s.py) `python`
- [Mounted Disk Capacity](System/mounted-disk-capacity.5s.sh) `shell`
- [Real Cpu Usage Chart](System/real-cpu-usage-chart.10s.sh) `shell`
- [Real Cpu Usage](System/real-cpu-usage.10s.sh) `shell`
- [Uptime](System/uptime.1m.sh) `shell`
- [Usbinfo](System/usbInfo.10s.py) `python`

#### Time
- [Fuzzyclock](Time/fuzzyclock.1s.py) `python`
- [Unixtime](Time/unixtime.5s.sh) `shell`

#### Tutorial
- [Cycle Text And Detail](Tutorial/cycle_text_and_detail.sh) `shell`
- [Is Bitbar](Tutorial/is_bitbar.sh) `shell`

#### Weather

##### ForecastIO
- [Weather](Weather/ForecastIO/weather.15m.py) `python`
- [Geoipweather](Weather/GeoIPWeather.15m.rb) `ruby`

##### OpenWeatherMap
- [Weather](Weather/OpenWeatherMap/weather.15m.py) `python`
- [Wunderground](Weather/Wunderground.30m.rb) `ruby`

#### Web

##### EasyDigitalDownloads
- [Edd](Web/EasyDigitalDownloads/edd.15m.py) `python`

##### HackerNews
- [Hacker News](Web/HackerNews/hacker_news.rb) `ruby`

##### OpenUI5
- [Openui5ver](Web/OpenUI5/openui5ver.1h.sh) `shell`

##### Reddit
- [Subreddit Links](Web/Reddit/subreddit_links.rb) `ruby`

##### StackOverflow
- [Reputationizer](Web/StackOverflow/reputationizer.5m.sh) `shell`\

There are some issues.. because they are really scripts, maybe we should use lower case?

**Comment by matryer** [comment]
Pretty good eh?

**Comment by dkhamsing** [comment]
lol i dunno

**Comment by dkhamsing** [comment]
Did you read this part

There are some issues

ELB is now elb
GeoIPWeather is now Geoipweather
iTunes is now Itunes
...
Because they are really scripts, maybe we should use lower case or leave unchanged capitalization?

Let me know what you think

**Comment by matryer** [comment]
One trick I’ve seen elsewhere is to have an explicit list of exceptions that is consulted first - which allows us to be explicit about the titles of those troublesome ones.

I think that’ll be a good solution for now? But we do want plugin management to evolve and mature as the library grows.

**Comment by dkhamsing** [comment]
Seems a little complicated but can be done

**Comment by dkhamsing** [comment]
Mat check out the latest https://github.com/dkhamsing/bitbar-plugins/tree/patch-2

These are white listed

```
    'cmus',
    'cpu',
    'elb',
    'GeoIPWeather',
    'itunes',
    'is bitbar',
    'openui5ver',
    'real cpu usage chart',
    'real cpu usage',
    'usbInfo',
    'vpn check',
    'wifiname'
```

**Comment by keithamus** [comment]
Hey @dkhamsing it looks like this needs rebasing, would you be so kind please?

**Comment by dkhamsing** [comment]
Yup

**Comment by dkhamsing** [comment]
@matryer ready

**Comment by dkhamsing** [comment]
Hm just realize this breaks the 'Available Plugins' link, will update

**Comment by dkhamsing** [comment]
It now starts like this

```
### Available Plugins 
61 plugins 

#### AWS 
- [elb](AWS/elb.30s.sh) `shell` 

#### Bitcoin 

##### bitstamp.net 
- [Last](Bitcoin/bitstamp.net/last.10s.sh) `shell` 
...
```

**Comment by dkhamsing** [comment]
@matryer @keithamus ready

**Comment by keithamus** [comment]
This LGTM but I'll let @matryer merge it in I think.

**Comment by matryer** [comment]
Do we think https://getbitbar.com means we no-longer need this?

**Comment by keithamus** [comment]
I'd say yes, pretty much so.

**Comment by matryer** [comment]
Well thank you for the contribution - a very inspiring idea.

**Comment by dkhamsing** [comment]
Cheers

**Pull request closed without merging**
