### PR TITLE
Convert to swift 3 (xcode8)

### PR DESCRIPTION
**Pull request by kenji21**
Just syntax issue, tested on Sierra with xcode8

### CODE REVIEW

**Comment by matryer** [comment]
@kenji21 please [see issues](https://travis-ci.org/matryer/bitbar-plugins/builds/169315664).

**Comment by kenji21** [comment]
swift3 is shipped since xcode8... .travis.yml have `osx_image: xcode7.1`, but such an update might generate issue for other plugins no ?

**Comment by kenji21** [comment]
let's force push to try with xcode8

**Comment by kenji21** [comment]
xcode8's travis image already has python 2.7 installed :

````
Error: python-2.7.12_1 already installed
To install this version, first `brew unlink python`
The command "brew install python && pip install pyflakes" failed and exited with 1 during .
````

**Comment by kenji21** [comment]
now it's node...
```
Error: node-6.7.0 already installed
To install this version, first `brew unlink node`
The command "brew install node && npm install -g jshint" failed and exited with 1 during .
```

**Comment by kenji21** [comment]
... xcode8 in osx_image of .travis.yml, but integration shows:

````
Xcode 7.3.1
Build version 7D1014
````

**Comment by iosdeveloper** [comment]
Does it work on your fork? Builds are always run with the .travis.yml from the master branch for security reasons.

**Comment by tresni** [comment]
I'll give this a test locally and see if I can do an xcode8.0 build.  I'm not sure it makes sense to use system python, while it might be "okay" for now, we may need additional packages/stuff in the future.

**Comment by kenji21** [comment]
same issue, xcode7.3 in build log from my clone : https://travis-ci.org/kenji21/bitbar-plugins/builds/170689787

**Comment by kenji21** [comment]
okay... image is not xcode8.0 but xcode8... (as of xcode8.1 is in GM, I have added the .0)

**Comment by kenji21** [comment]
ok, now ./System/trackpad-dot.1h.swift has also to be converted to swift3.
And there are some shell issues: https://travis-ci.org/kenji21/bitbar-plugins/builds/170691816

````
failed linting with "shellcheck"
````

**Comment by tresni** [comment]
@kenji21 don't worry about the failing shellcheck issues.  That happens as new shellcheck versions are released.  We could pin the version (I think) but I like that we require scripts be updated to meet latest Best Practices if they are updated.

Same applies for the trackpad-dot script.  Your PR shouldn't end up testing that script, but future edits to it will require that the script be upgraded to Swift3.

**Comment by kenji21** [comment]
putting script inside a xcode playground and converting to "current swift syntax" is not vert hard ;-)
build is queued

**Comment by kenji21** [comment]
Two swift are now OK for swift3, but got a warning :
````
./System/Battery/battery-dot.1h.swift missing recommended metadata for desc
````
but comment is present at top of file (lines 8 & 9):

```
* <bitbar.desc>Displays a coloured dot for trackpad, keyboard and laptop battery in the menu bar that changes from green to yellow to red the lower the power gets - based on       the trackpad-dot plugin by Manu Wallner (https://getbitbar.com/plugins/System/trackpad-dot.1h.swift).
         The plugin uses ANSI colors to display all three battery levels next to each other - the downside is that it's limited to the ANSI colors - so no orange available</bitbar.desc>
```

**Comment by tresni** [comment]
We don't like things that contain line breaks.  Given desc is option, I'm not too worried about it :)

**Comment by tresni** [comment]
Only thing now I would like is a comment on why you choose to not use homebrew for node/python.  Did using homebrew cause something to fail?

**Comment by kenji21** [comment]
due to errors like:
```
Error: node-6.7.0 already installed
To install this version, first `brew unlink node`
```

but this error was with "xcode8.0" osx_image... I revert

**Comment by kenji21** [comment]
I think xcode8 image has already installed python 2.7... https://travis-ci.org/matryer/bitbar-plugins/builds/171155403

````
Error: python-2.7.12 already installed
To install this version, first `brew unlink python`
The command "brew install python && pip install pyflakes" failed and exited with 1 during .
````
I think, the travis.yml should be updated: https://docs.travis-ci.com/user/osx-ci-environment/#A-note-on-upgrading-packages

**Comment by tresni** [comment]
Thanks for pointing that out. I'll get your changes merged in and the travis.yml file updated for best practices!

**Comment by tresni** [comment]
Working on getting travis.yml updated right now to support 7.3 (dealing with the `brew install` vs `brew outdated && brew upgrade`), then will pull in 8.0 changes.

**Comment by tresni** [comment]
Closing in favor of #620 .

**Pull request closed without merging**
