### PR TITLE
New plugin: Hacker News improved version.

### PR DESCRIPTION
**Pull request by manorie**
I have noticed some issues with the old plugin,
- When system reboots, while trying to access to the net plugin gives an error.
- Makes too many requests and needs manual refresh.
- Does not have support to show an interesting(with most score) news title in bar.

This plugin I am sending with PR,
- Does not need a refresh,
- Do not raise an error on system reboot or wireless disconnection,
- Keeps previous news in a small *.txt file and remove them with a TIME_OUT variable (default 10 minutes) news by news, 
- More performant and fail-safe then previous one.
- Sorts news according to their score and puts first one's title to the bar.

Hope you like it.

### CODE REVIEW

**Comment by keithamus** [comment]
Hey @manorie thanks for the PR. Rather than making a new plugin for this, could you apply your changes to the existing plugin? This way we don't have loads of plugins all doing the same thing.

**Comment by keithamus** [comment]
Also /cc @caneroj1 @thameera @oliviernt

**Comment by manorie** [comment]
Hey @keithamus I just did not want to be rude to modify existing plugin. But great idea, I will improve the old one - I am using this one I coded for couple days have little more improvements in my mind.
I will finish them and update the PR.

Thanks,

**Comment by keithamus** [comment]
@manorie understandable 😄. Look forward to seeing the updated PR

**Comment by manorie** [comment]
Updated PR @keithamus @caneroj1 @thameera @oliviernt ,

Thanks.

**Comment by tresni** [comment]
If there are no objections within the next day I'll merge this in

**Comment by caneroj1** [comment]
Looks good to me!

**Pull request merged**
