### PR TITLE
Add jira tickets plugin

### PR DESCRIPTION
**Pull request by ryansydnor**
This plugin will display all tickets assigned to the user that
are currently open and group them by status.

### CODE REVIEW

**Comment by tresni** [comment]
There is already a [JIRA plugin](https://getbitbar.com/plugins/Dev/Jira/jira.1m.sh).  Per @keithamus' comment in #362:

> [T]he plugins repo is more of a showcase than something like `pypi` or `npm`. Fixes for different problems, over different fixes for the same problems :smile:.

Does your plugin offer additional functionality over the existing JIRA plugin?

**Comment by ryansydnor** [comment]
@tresni - fair. A few things:

1. I couldn't get the other plugin to run easily (kept crashing Bitbar completely, actually)
2. I didn't like the fact the other plugin didn't categorize tickets by status. 
3. In Jira, every team has different workflows and potentially custom status field values. The other plugin doesn't account for that kind of thing.
4. There's a bit of "reinventing the wheel" in the other plugin. There's always a tradeoff, but I feel that leveraging a library to handle talking to Jira greatly simplifies the maintenance burden on the bitbar plugin.

Just some thoughts. Happy to close the PR if you don't think they're valid :)

**Comment by keithamus** [comment]
@ryansydnor perhaps you would consider adding features and fixing bugs in the existing Jira plugin?

**Comment by ryansydnor** [comment]
@ngehlert - as the original author, what do you think? Does the tradeoff between maintainability, flexibility, and features at the expense of an extra dependency warrant swapping out your Jira plugin? If not, I'm happy to close this PR.

**Comment by ngehlert** [comment]
@ryansydnor i'll have a look at the new plugin. but since it apparently introduces a new dependency i'm already not a big fan. 
i edit this comment in a couple of minutes

**Comment by ryansydnor** [comment]
Ok! I'll close this in favor of the existing one. 

It sounds like a configuration driven flag could be a great solution to the various grouping mechanisms. Looking forward to config being implemented.

**Pull request closed without merging**
