### PR TITLE
MAS support

### PR DESCRIPTION
**Pull request by tresni**
FAO: @kdeldycke

[mas](https://github.com/argon/mas) allows you to manipulate Mac AppStore applications from the command line.  In it's current version it does not display information on the installed version of the application.  Watch argon/mas#26 for potential fixes.  For now, `installed_version` is reported as `''` which works pretty well:

screenshot

Also, did some cleanup on how `stderr` is handled and displayed.  Much cleaner now w/ less whitespace and doesn't display warnings as errors. (`process.returncode` check for truthiness.)

### CODE REVIEW

**Comment by kdeldycke** [comment]
Good job! Let's merge this! :)

**Comment by argon** [comment]
@tresni https://github.com/argon/mas/pull/45 adds the currently installed version to the `mas outdated` command for each application.

This should allow you to supply the `installed_version` information you need.

**Comment by kdeldycke** [comment]
Thanks @argon for the hint! Just added an issue at https://github.com/kdeldycke/meta-package-manager/issues/4 , as `package_manager.py` development now happens over there.

**Comment by kdeldycke** [comment]
@argon : Done in v1.10.1. Waiting for a merge at: https://github.com/matryer/bitbar-plugins/pull/578 .

**Pull request merged**
