### PR TITLE
Use new GitHub status API

### PR DESCRIPTION
**Pull request by masutaka**
FAO: (@blockloop)

## Why?

:link: https://status.github.com/messages

deprecated message

## Previous response

```
$ curl -s https://status.github.com/api/last-message.json | jq
{
  "status": "good",
  "body": "Everything is operating normally.",
  "created_on": "2018-12-18T18:26:50Z"
}
```

## Current response

```
$ curl -s https://kctbh9vrtdwd.statuspage.io/api/v2/status.json | jq
{
  "page": {
    "id": "kctbh9vrtdwd",
    "name": "GitHub",
    "url": "https://www.githubstatus.com",
    "time_zone": "Etc/UTC",
    "updated_at": "2019-02-26T06:57:45.424Z"
  },
  "status": {
    "indicator": "none",
    "description": "All Systems Operational"
  }
}
```

See https://www.githubstatus.com/api

### CODE REVIEW

**Comment by tockrock** [comment]
BTW, the current "Current response" in this PR's message seems to be for [`https://kctbh9vrtdwd.statuspage.io/api/v2/summary.json`](https://kctbh9vrtdwd.statuspage.io/api/v2/summary.json) and not the [`https://kctbh9vrtdwd.statuspage.io/api/v2/status.json`](https://kctbh9vrtdwd.statuspage.io/api/v2/status.json) that this PR uses.

**Comment by masutaka** [comment]
Oops... Just fixed. Thanks!

**Comment by tockrock** [comment]
Thanks for fixing the PR message!

To: @matryer @blockloop 

Looks like the old endpoint is getting brownedout and less then 1 week until it's disabled.
It would be great if this gets merged in.

[](https://status.github.com/messages)

# Travis issue

The current failure in travis seems to be caused by the recent version of [`parallel` that's used in `rubocop`](https://github.com/rubocop-hq/rubocop/blob/8c3b000521aa609ab334ea64b803bd21ea25fcd1/lib/rubocop/runner.rb#L3) now [requires Ruby >=2.2](https://github.com/grosser/parallel/commit/1ff3469d4f287f6a81fde2e1ca5f1ff135ec8528#diff-f24495dc345db280596f47c1a254dc91).

Since this seems like something that's effect Travis in general, and would require more consideration how to handle the issue, and out of scope of this PR.

**Comment by gingerbeardman** [comment]
Please solve the outstanding Travis CI issue(s) so this can be merged! Many thanks.

You can close and reopen the PR to get Travis to try again, see #1214

**Comment by masutaka** [comment]
@gingerbeardman Thanks! Travis CI has just passed. :tada:

**Pull request merged**
