### PR TITLE
Add SSH plugin

### PR DESCRIPTION
**Pull request by thameera**
screen shot 2016-01-10 at 12 08 18 am

I added this under Network section, but not entirely sure if that's the right place to put that in.

### CODE REVIEW

**Comment by manojlds** [comment]
This should probably be in `Dev`?

**Comment by C4Wiz** [comment]
how do you format the config file?

**Comment by thameera** [comment]
@C4Wiz Like a regular SSH config file. Eg: https://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/

**Comment by C4Wiz** [comment]
ok thanks. i got it all cofigured generated keys. now when i use the plugin to connect to the server it asks for the passphrase for the key i generated, if i still have to type a password, whats the point?

**Comment by C4Wiz** [comment]
got it thanks

**Pull request merged**
