### PR TITLE
Upgrade sensibo.60s.sh to the latest version (1.2.1)

### PR DESCRIPTION
**Pull request by niladam**
This updates sensibo.60s.sh to the latest version, where the Fahrenheit temperature is correctly displayed.

### CODE REVIEW

**Comment by niladam** [comment]
hey @tresni - apparently the check failed again -- however -- not to the plugin upgrade. It appears to have failed because of zsh completion (see attached) ?

Screenshot 2020-01-21 13 53 45

Can you maybe retry the check ?

Thanks :)

**Comment by tresni** [comment]
Actually failed because it couldn't install python, that's a new one

**Comment by tresni** [comment]
closing and reopening to get new travis.yml

**Comment by niladam** [comment]
Thank you for the merge @tresni !:)

**Pull request merged**
