### PR TITLE
add DNS switcher plugin

### PR DESCRIPTION
**Pull request by saiqulhaq**
Hi
I just wrote DNS switcher plugin

screenshot copy

some sites are banned by my internet network provider 
I can't access them through Google DNS
so I often change my network DNS on Network Preferences

I have tried this blog post http://osxdaily.com/2013/07/01/change-network-location-quickly-mac-os-x/ for alternative, but it will disconnect and reconnect the connection, it's bad for me

### CODE REVIEW

**Comment by matryer** [comment]
What if the top line showed the current selection? Is that easy?

**Comment by matryer** [comment]
p.s. awesome plugin idea :D

**Comment by saiqulhaq** [comment]
Nice idea
I will try

**Comment by matryer** [comment]
Let me know when you've done it and I'll merge it in.

**Comment by saiqulhaq** [comment]
Hi @matryer
please review my last commit

screen shot

It will show the DNS IP address on the second line if the DNS is unrecognized by script 

and unfortunately we have to refresh the plugin manually to refresh displayed DNS (top line)
I have checked this pull request https://github.com/matryer/bitbar/pull/134
but it seems not working on my bitbar app

**Comment by matryer** [comment]
Why does the plugin need to be refreshed manually? What version of BitBar are you running?

**Comment by matryer** [comment]
p.s. I don't think `(DNS)` is needed - with the context, it's clear what it is I think. And it'll be neater. What do you think?

**Comment by saiqulhaq** [comment]
> Why does the plugin need to be refreshed manually? What version of BitBar are you running?

I am using V1.4-beta.2

> p.s. I don't think (DNS) is needed - with the context, it's clear what it is I think. And it'll be neater. What do you think?

Yes you're right, it's more neater now

**Pull request merged**
