### PR TITLE
Fixing character encoding in reading file.

### PR DESCRIPTION
**Pull request by raguay**
I just fixed a problem with character encoding. I couldn't figure out a fast forward on my fork, so I re-forked and added the todoNotePlan plugin. But, it is acting like it is a new item. Sorry, not the best at using GitHub.

### CODE REVIEW

**Comment by raguay** [comment]
Added some more options and fixed a few items. Help from others as well.

**Comment by raguay** [comment]
Added some more cleaning up.

**Comment by raguay** [comment]
Last minute fix for checking if the file exists or not.

**Comment by tresni** [comment]
TravisCI is reporting a [rubocop linting error](https://travis-ci.org/matryer/bitbar-plugins/builds/234725959#L1815). Looks like you may have inadvertantly changed the indentation around line [90](https://github.com/matryer/bitbar-plugins/pull/770/files#diff-db6335bcf5ce441be186676241260b0cR90) - [106](https://github.com/matryer/bitbar-plugins/pull/770/files#diff-db6335bcf5ce441be186676241260b0cR106)

**Comment by raguay** [comment]
I fixed the formatting (I think). Give this a try. Thanks.

**Comment by tresni** [comment]
Now it's catching a different indentation issue at line 104 :-(  If you want (as long as it's just indentation errors) happy to clean it up on my side, I'm guessing your version of rubocop is just slightly off from what travis ci is using.

**Comment by raguay** [comment]
Just pushed it. That is weird that it would not catch that one? Thanks.

**Pull request merged**
