### PR TITLE
Add GitHub Notifications

### PR DESCRIPTION
**Pull request by dkhamsing**
screenshot

### CODE REVIEW

**Comment by matryer** [comment]
Is this significantly different to https://github.com/matryer/bitbar-plugins/blob/master/Dev/GitHub/notifications.30s.py ?

**Comment by dkhamsing** [comment]
aw sad.. let me try it.. seems pretty close

**Comment by dkhamsing** [comment]
how'd you choose to merge his first??

**Comment by matryer** [comment]
Sorry - it was nearer the top and I didn't notice yours (although I think you submitted first).

**Comment by matryer** [comment]
Let's agree on the best one and go with that. Please do add your name to the contributors list :)

**Comment by dkhamsing** [comment]
No worries
Thank you for BitBar

**Comment by dkhamsing** [comment]
At a glance differences are

- ruby vs python 
- multiple vs single account support 
- possible href issue on his for issue notifications 
- less code for python version 

Can we list both ?

**Comment by dkhamsing** [comment]
screen shot 2016-01-07 at 4 53 04 pm
screen shot 2016-01-07 at 4 53 10 pm

**Comment by dkhamsing** [comment]
yeah basically the same :sweat_smile:

**Pull request closed without merging**
