### PR TITLE
Toggle for Cisco AnyConnect Umbrella Protection

### PR DESCRIPTION
**Pull request by levensailor**
Enable or Disable / Display Status of Umbrella agent. Sometimes disabling the agent to allow browsing to websites with false-positives.

### CODE REVIEW

**Comment by tresni** [comment]
Your script needs to be made executable.  This can normally be accomplished by doing the following:

```
chmod +x /path/to/your/script.sh
git add /path/to/yout/script.sh
git commit -m "Making script executable"
git push origin master
```

**Comment by levensailor** [comment]
image

**Comment by tresni** [comment]
It's not according to git:

```
Projects/bitbar-plugins ●» git checkout https://github.com/matryer/bitbar-plugins/pull/1049/files
remote: Counting objects: 8, done.
remote: Total 8 (delta 4), reused 4 (delta 4), pack-reused 4
Unpacking objects: 100% (8/8), done.
From github.com:matryer/bitbar-plugins
 * [new ref]         refs/pull/1049/head -> levensailor-master
Switched to branch 'levensailor-master'
Projects/bitbar-plugins ●» cd System
bitbar-plugins/System ●» ls -al umbrella*
-rw-r--r--  1 bhartvigsen  staff  1332 Aug 25 10:01 umbrella.5s.sh
bitbar-plugins/System ●» 
```
So, either you've managed to have git ignore file permissions, or you haven't pushed a commit that contains the file permission change.

**Comment by tresni** [comment]
Merged with  25af5b6

**Pull request closed without merging**
