### PR TITLE
Adding fastlane plugin

### PR DESCRIPTION
**Pull request by RishabhTayal**
Run [fastlane](https://github.com/fastlane/fastlane) directly from menu bar!

screenshot 2018-05-18 13 19 50

### CODE REVIEW

**Comment by RishabhTayal** [comment]
@tresni thanks for merging. When does the plugin show up on getbitbar.com?

**Comment by tresni** [comment]
Website builds automatically once a day. So within the next 24 hours

**Comment by RishabhTayal** [comment]
I still don't see my plugins there. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
Check the dev section: https://getbitbar.com/plugins/Dev

The Google Custom Search Engine is not surfacing the changes... yet

**Comment by RishabhTayal** [comment]
I don't see it under the dev section as well. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
I see this:

screen shot 2018-05-24 at 19 39 11

**Comment by RishabhTayal** [comment]
That's really strange. I don't see that in my browser. Here is a screenshot of text Search on the page. 

GitHawk Upload by RishabhTayal

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
That is odd, must be a cached on your device? Try opening the page in a private tab.

I see two of yours on the Dev page, one near the top one near the bottom.

**Comment by RishabhTayal** [comment]
Aah. I tried different browser (on my computer) and now it's showing. 👍  Sorry to bother you.

**Pull request merged**
