### PR TITLE
Update GeoIPWeather

### PR DESCRIPTION
**Pull request by dkhamsing**
1. Old api key stopped working.. :confused: 
- Added metadata 

weather

### CODE REVIEW

**Comment by keithamus** [comment]
I'm guessing the old api key stopped working because it isn't meant to be public?

Could you please refactor it so it is a variable that people can set, like other scripts do. See [Wunderground.30m.rb's use of API_KEY for reference.](https://github.com/matryer/bitbar-plugins/blob/master/Weather/Wunderground.30m.rb#L260)

**Comment by dkhamsing** [comment]
Yup for sure

**Comment by keithamus** [comment]
Alternatively, @dkhamsing, it looks like OpenWeatherMap can add an exception to the API key if it used in an open source way:

> **For FOSS developers**: we welcome [free](http://www.gnu.org/philosophy/free-sw.html) and [open source](http://opensource.org/osd-annotated) software and are willing to help you. If you want to use OWM data in your free software application [please register an API key](http://home.openweathermap.org/users/sign_in) and [file a ticket describing your application and API key registered.](https://openweathermap.desk.com/customer/portal/emails/new) OWM will review your request lift access limits for your key if used in open source application.

Maybe we should do that?

**Comment by dkhamsing** [comment]
Can do both

**Comment by keithamus** [comment]
That'd be awesome :smile:

**Comment by dkhamsing** [comment]
Contacted OWM, will keep you posted

openweathermap email us
openweathermap email us - thank you

**Comment by dkhamsing** [comment]
@keithamus ready

**Comment by keithamus** [comment]
:+1: :moneybag:

**Comment by dkhamsing** [comment]
:tada:

**Comment by matryer** [comment]
:tada:

**Comment by dkhamsing** [comment]
> Support <support@openweathermap.desk-mail.com>	Fri, Jan 22, 2016 at 10:09 PM
> Reply-To: support@openweathermap.desk-mail.com
> Subject: Lift limits / use OWM data in free software
> JAN 23, 2016  |  06:09AM UTC 
> Ivan replied:
> Thank you for choosing our services, Your APPID has been put into the FOSS keys list. Some time can pass before this gets propagated to the servers.
> 
> Best regards, 
> Ivan Mashchenko 
> 
> OpenWeatherMap team 
> http://openweathermap.org 
> info@openweathermap.org

**Comment by keithamus** [comment]
:tada: :100:. If only every api provider did this!

**Comment by dkhamsing** [comment]
cc @taylorzane

**Comment by taylorzane** [comment]
Nice! Thanks @dkhamsing.

**Pull request merged**
