### PR TITLE
Plugin to toggle ethernet network on and off

### PR DESCRIPTION
**Pull request by davidshr10**
OSX by default does not provide option to toggle ethernet connections on and off
on the menubar, hence this script provides that capability.

### CODE REVIEW

**Comment by davidshr10** [comment]
This is a demo screenshot
screen shot 2018-07-15 at 12 13 24 am

**Comment by gingerbeardman** [comment]
It would also be cool to either

`open x-apple.systempreferences:com.apple.preference.network`

or

`open /System/Library/PreferencePanes/Network.prefPane`

but I can't get either to work from BitBar after a brief try

**Comment by gingerbeardman** [comment]
OK, I figured it out. Add this to the bottom of the script

```bash
echo "---"
echo "Network Preferences | bash='$0' param1=launch-system-preferences terminal=false refresh=true"
if [ "$1" = 'launch-system-preferences' ]; then
  open /System/Library/PreferencePanes/Network.prefPane
fi
```

**Comment by davidshr10** [comment]
Thank you for the suggestions. I've added the Network Preferences in the menu and also resized the icon. I don't have the best skills for image editing but the icon could be thinner by a pixel.

**Comment by gingerbeardman** [comment]
What do you think about this icon?

screen shot 2018-07-15 at 17 40 18

```
network_icon="iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFiUAABYlAUlSJPAAAAD6SURBVGhD7ZhBCoNAEASFPCvPSm75aC6+JdkW5+ASw6xOzy7SBYMiw3aXxEsmIYQQQojrcF+vDJhnb3iV+azXaJhnb7Agm8hA5tkb6qDoMPb5CykhBWpOloRBycuWMEJze0kYIfm9JYxTPUaRMA71GU3CaOrlXb6VeZaZ18E9ntVE77n6eSXAo0y9i2c10Xvgb88WCfAuU+/jWU30nrHb9zIioEUm+ifj3QOunl4ZfIgIwlvD4H7vI47c8/ZbaFpO5FCv0WRO9RlFJqRHb5nQ/F4ylNxsGWpelkxKDjskRcKow5giNAnDAhlBzLN/com/TIUQQgghqEzTFxVIQVQVpJ49AAAAAElFTkSuQmCC"
```

**Comment by gingerbeardman** [comment]
Excellent! Thank you for this contribution.

**Pull request merged**
