### PR TITLE
Create Bitcurex

### PR DESCRIPTION
**Pull request by Bicki**

### CODE REVIEW

**Comment by tresni** [comment]
So the first issue is that you don't have a file extension, do this:

```
git mv Bitcoin/Bitcurex Bitcoin/Bitcurex.sh
```

Also, it will currently only fetch new information when the user refreshes all plugins.  If you want it to check (e.g.) once an hour, do this:

```
git mv Bitcoin/Bitcurex.sh Bitcoin/Bitcurex.1h.sh
```
If you want to run the tests locally, make sure you have [shellcheck](https://github.com/koalaman/shellcheck) installed (`brew install shellcheck` if you run homebrew.)  If not, just push those changes to your branch.  Travis will see the new commits and re-run the tests.  You'll need to fix any issues that Travis identifies.

**Comment by Bicki** [comment]
done

**Comment by tresni** [comment]
Check the Travis build results for errors you need to fix:

```
ERR! /Users/travis/build/matryer/bitbar-plugins/Bitcoin/Bitcurex.10s.sh missing required metadata for author.github
```

Make sure you have `<bitbar.author.github>Bicki</bitbar.author.github>` metadata in your script. It's required. You can optionally add an image and description tag too. 

```
ERR! /Users/travis/build/matryer/bitbar-plugins/Bitcoin/Bitcurex.10s.sh not executable
```

Run `chmod +x Bitcurex.10m.sh` then git add and commit that. 

There is also one shellcheck error. Simply wrap `$result` in double quotes (`"$result"`) in your printf.

**Comment by Bicki** [comment]
Metadata and quotes is corrected, I dont know how to change permission from the web site, any tip? Is there any command line?

**Comment by tresni** [comment]
You can't from the website. You need to do it on your local machine. If that's going to be an issue let me know. 

-- Brian

**Comment by Bicki** [comment]
Its a little problem for me. Its my first time on github. I cant install github desktop with command line tools, because I've ML 10.8. I'am not "programmer" and I dont know to much about remote connection with ssh. Can you do this for me or just give me any tip about how can I configure my terminal? Thanks

**Comment by tresni** [comment]
On the terminal it would just be (assuming you are starting in the bitbar-plugins root folder)

```sh
chmod +x Bitcoin/Bitcurex.10m.sh
git add Bitcoin/Bitcurex.10m.sh
git commit -m "Making it executable"
git push origin # Assuming origin is the name of your remote
```
I've gone ahead and done that for you in commit b919cfc22ddc4 and testeded locally.  That has now been pushed to master.

**Pull request merged**
