### PR TITLE
Added Trello Plugin

### PR DESCRIPTION
**Pull request by kodie**

### CODE REVIEW

**Comment by kodie** [comment]
@matryer 

It says my Travis CLI check failed with a `The command "brew install python && pip install pyflakes" failed and exited with 1 during .` error but this is a bash plugin?

**Comment by tresni** [comment]
I'll be merging a change shortly that fixes that and then rebuild all the pending PRs to see if they go green.

**Comment by kodie** [comment]
@tresni Sounds good! Thanks!

**Comment by tresni** [comment]
Have to close and re-open to pickup the travis-ci config changes.

**Pull request merged**
