### PR TITLE
Add a generic package manager plugin.

### PR DESCRIPTION
**Pull request by kdeldycke**
Currently supports Homebrew and Cask.

I plan to add others like Python's `pip` in future revisions.

### CODE REVIEW

**Comment by tresni** [comment]
Please host the image externally (imgur seems to be a popular choice.) This repo only contains scripts, not their screenshots or other ancillary data.

**Comment by kdeldycke** [comment]
@tresni : should I also convert my image to jpeg? Travis tests do not recognise PNG: https://travis-ci.org/matryer/bitbar-plugins/builds/142523996#L346

**Comment by tresni** [comment]
No, you need to remove it completely from your PR and host it externally (using your dot-files repo works, but I'd usually recommend an image hosting service such as imgur or imageshack.)

**Comment by kdeldycke** [comment]
@tresni : done. Also fixed a tiny issue about multiline description in metadata.

**Comment by tresni** [comment]
👍  Going to start using this myself, nice work :)

**Comment by kdeldycke** [comment]
Thanks for the merge! That was fast! :)

**Pull request merged**
