### PR TITLE
Migrate to Python 3, add seven day forecast to drop down menu, and …

### PR DESCRIPTION
**Pull request by poolis**
…enable location name instead of finding OpenWeatherMaps location id.

### CODE REVIEW

**Comment by matryer** [comment]
@poolis This has conflicts now? Also, I wonder if you could take a screenshot of it running and include the image metadata?

**Comment by matryer** [comment]
@poolis does this conflict tell us that somebody else has already fixed this?

**Comment by poolis** [comment]
Conflict was just someone updating copyright.  
Screen Shot 2021-02-12 at 9 45 21 AM

**Comment by matryer** [comment]
Thanks @poolis - could you set the `<bitbar.image>` metadata field please?

**Comment by poolis** [comment]
@matryer Need anything else for this?

**Comment by matryer** [comment]
No @poolis, thanks. It's in. :)

**Pull request merged**
