### PR TITLE
Add plugin battery health

### PR DESCRIPTION
**Pull request by tanrax**

### CODE REVIEW

**Comment by tresni** [comment]
Please review the Travis-CI build errors.  Looks like you need to `chmod +x` your script and address some quoting issues.

**Comment by tanrax** [comment]
would not pass. so again not upload the file to execute permissions.

https://travis-ci.org/tanrax/bitbar-batteryHealth

https://github.com/tanrax/bitbar-batteryHealth

**Comment by tresni** [comment]
The other issues can be seen by visiting the "Details" link for the Travis-CI integration below.  But for easy of fixing, here's the output:

```
ERR! /Users/travis/build/matryer/bitbar-plugins/System/battery_health.60s.sh failed linting with "shellcheck", please correct the following:
In /Users/travis/build/matryer/bitbar-plugins/System/battery_health.60s.sh line 37:
    changeStatus "Battery Low" $BATTERY% "Blow"
                               ^-- SC2086: Double quote to prevent globbing and word splitting.
In /Users/travis/build/matryer/bitbar-plugins/System/battery_health.60s.sh line 47:
    changeStatus "Battery high" $BATTERY% "Blow"
                                ^-- SC2086: Double quote to prevent globbing and word splitting.
In /Users/travis/build/matryer/bitbar-plugins/System/battery_health.60s.sh line 51:
if [ $BATTERY -le $POR_LOW ] && [ $LOW = False ]; then
     ^-- SC2086: Double quote to prevent globbing and word splitting.
In /Users/travis/build/matryer/bitbar-plugins/System/battery_health.60s.sh line 53:
elif [ $BATTERY -ge $POR_HIGH ] && [ $HIGH = False ]; then
       ^-- SC2086: Double quote to prevent globbing and word splitting.
In /Users/travis/build/matryer/bitbar-plugins/System/battery_health.60s.sh line 55:
elif [ $BATTERY -le $POR_HIGH ] && [ $BATTERY -ge $POR_LOW ]; then
       ^-- SC2086: Double quote to prevent globbing and word splitting.
                                     ^-- SC2086: Double quote to prevent globbing and word splitting.
In /Users/travis/build/matryer/bitbar-plugins/System/battery_health.60s.sh line 63:
if [ $TYPE = 'AC' ]; then
     ^-- SC2086: Double quote to prevent globbing and word splitting.
In /Users/travis/build/matryer/bitbar-plugin
```

**Comment by tanrax** [comment]
I'm thinking translate the code to Python XD

**Comment by tanrax** [comment]
Check!

**Pull request merged**
