### PR TITLE
Create Offlineimap notification

### PR DESCRIPTION
**Pull request by tanrax**

### CODE REVIEW

**Comment by tresni** [comment]
Travis errored out.  Requesting a rebuild.

**Comment by tresni** [comment]
You PR also contains battery_health.2s.py.  Are you rebased on the current master as I belive that change was merged with #435 

```
$ git remote add upstream https://github.com/matryer/bitbar-plugins.git
$ git fetch upstream
$ git checkout master
$ git rebase upstream/master
$ git push origin master
```

You may need to fix up merge conflict and the like.

**Comment by tanrax** [comment]
Sorry for the inconvenience. Now it works?

**Comment by keithamus** [comment]
@tanrax looks like you probably need another rebase. This features some code from the upstream branch

**Comment by tanrax** [comment]
`warning: 3 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Removing System/battery_health.60s.sh
Applying: Add Offlineimap
Applying: Add plugin battery health
Applying: Change permissions
Applying: Fix doble quotes
Applying: News fixs
Applying: Add image
Applying: Update version
Applying: Add Offlineimap
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Andros-MacBook:bitbar-plugins androsfenollosa$ git push origin master
To https://github.com/tanrax/bitbar-plugins
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/tanrax/bitbar-plugins'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Andros-MacBook:bitbar-plugins androsfenollosa$`

**Comment by keithamus** [comment]
@tanrax simply run `git push origin master --force` and it should work

**Comment by tanrax** [comment]
@keithamus woriking?

**Comment by keithamus** [comment]
👍

**Pull request merged**
