### PR TITLE
Add Gerrit incoming code reviews plugin

### PR DESCRIPTION
**Pull request by ryansydnor**

### CODE REVIEW

**Comment by tresni** [comment]
bitbar.image should be a screenshot of your plugin in action vs a logo for the service you are connecting to.  Can you update the PR to include a screenshot instead?

**Comment by ryansydnor** [comment]
whoops! sure.

**Comment by tresni** [comment]
Image is optional, you get higher placement on the website iirc if you have an image :)

**Comment by ryansydnor** [comment]
Thanks, @tresni !

**Pull request merged**
