### PR TITLE
Add bitping

### PR DESCRIPTION
**Pull request by SimonSays13**
Sends pings to one or more sites, display connectivity status, record results to file (separated daily) and graph the last X minutes performance via the dropdown with no external dependencies

### CODE REVIEW

**Comment by matryer** [comment]
@SimonSays13 see the [error](https://travis-ci.org/matryer/bitbar-plugins/builds/188947349).

**Comment by tresni** [comment]
@SimonSays13 it looks like you may have accidently undone all your changes in e2c5267.  I would recommend doing the following:

```sh
cd /path/to/root/bitbar/plugins/folder
git reset --hard e2c5267 # Move back to the good commit (just needs chmod +x)
chmod +x Network/bitping.10s.sh # make it exectable
git add Network/bitping.10s.sh
git push --force origin master # assuming your remote is named origin ;-)
```

**Comment by SimonSays13** [comment]
I used chmod +x Network/bitping.10s.sh on the file in the repository and then selected that file for upload for this commit

**Comment by SimonSays13** [comment]
I give up: still getting not executable error from travis

**Comment by tresni** [comment]
Made executable in e601b42ebdd63dc4852053adee9815609741f209 and merged in de041cbcdfb50e10edc99a892afe0a9e9b8d2734

**Pull request closed without merging**
