### PR TITLE
Add Twitch livestreamer plugin

### PR DESCRIPTION
**Pull request by gorangajic**
Because twitch.tv use flash it's better to use [livestreamer](http://docs.livestreamer.io/) to watch streams. This plugin lists top 10 streams by game and when clicked open in vlc using livestreamer

screen shot 2016-01-08 at 8 44 35 pm

### CODE REVIEW

**Comment by keithamus** [comment]
Hey @gorangajic this looks good! 

@matryer I think this is a good time to bring up the point that we should look to add a `CONTRIBUTING.md` for this repo, enforcing some rules around what can be uploaded. The reason I say this is because a default Mac OSX install includes Python, Ruby and Bash - but not Node. I think the bitbar-plugins repo should only contain plugins that would work with an out-of-the-box experience, and not rely on the user installing dependencies or other runtimes. Thoughts?

**Comment by gorangajic** [comment]
yup I agree with you. I have created this for me and want to share so anyone can reuse this if they find it useful.

I can probably figure out how to write this in Python or Ruby, but will probably take more time than writing  it in Javascript so that's why I used Node.js.

**Comment by keithamus** [comment]
@gorangajic I wouldn't expect you to rewrite it (unless you really want to) - but I can refactor it if need be. But I think let's see what @matryer has to say before we go any further.

**Comment by matryer** [comment]
I know what you mean - there's something very nice about just being able to drop the plugins into a folder and have it run. However, I'd hate to lose awesome plugins just because they have external dependencies. Some plugins will require API keys, others will have more significant dependencies. Perhaps the new [BETA metadata](https://github.com/matryer/bitbar-plugins/issues/53) stuff I'm playing around with is a good place to list dependencies?

**Comment by keithamus** [comment]
@matryer :ok_hand: having some way to enumerate what dependencies are needed would be a great idea.

**Comment by matryer** [comment]
... keeping them dependency free is also nice!

**Comment by Derimagia** [comment]
I'm interested in creating some plugins in node and would love to see some other plugins in node.

I understand keeping everything dependency free but it would be nice to list them and just make sure it's known that they require node.

I also just noticed that @sindresorhus just created a Bitbar node client at https://github.com/sindresorhus/bitbar which I'm inclined to take advantage of.

**Comment by Derimagia** [comment]
We should probably move the Dependency conversation to another thread.

To get back on topic about this Plugin, @gorangajic I like the idea of the plugin but it looks like it's specifically styled for Dark Mode. It looks a bit unreadable.

http://i.imgur.com/OG4JdIX.png

**Comment by gorangajic** [comment]
ups @Derimagia, updated commit that does not set color to white

**Pull request merged**
